// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// affinity
NumericMatrix affinity(NumericMatrix& dat, int n_wl, int n_dm, int nk, int H, int seed);
RcppExport SEXP _EDGE_affinity(SEXP datSEXP, SEXP n_wlSEXP, SEXP n_dmSEXP, SEXP nkSEXP, SEXP HSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type n_wl(n_wlSEXP);
    Rcpp::traits::input_parameter< int >::type n_dm(n_dmSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(affinity(dat, n_wl, n_dm, nk, H, seed));
    return rcpp_result_gen;
END_RCPP
}
// clip4
NumericVector clip4(NumericVector x, double inner, double outer);
RcppExport SEXP _EDGE_clip4(SEXP xSEXP, SEXP innerSEXP, SEXP outerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type inner(innerSEXP);
    Rcpp::traits::input_parameter< double >::type outer(outerSEXP);
    rcpp_result_gen = Rcpp::wrap(clip4(x, inner, outer));
    return rcpp_result_gen;
END_RCPP
}
// opt_epoch
NumericMatrix opt_epoch(NumericMatrix& embedding, IntegerMatrix& pairs, IntegerVector& adjust, IntegerVector& nns, NumericVector& abg, double alpha);
RcppExport SEXP _EDGE_opt_epoch(SEXP embeddingSEXP, SEXP pairsSEXP, SEXP adjustSEXP, SEXP nnsSEXP, SEXP abgSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type embedding(embeddingSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type adjust(adjustSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type nns(nnsSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type abg(abgSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(opt_epoch(embedding, pairs, adjust, nns, abg, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EDGE_affinity", (DL_FUNC) &_EDGE_affinity, 6},
    {"_EDGE_clip4", (DL_FUNC) &_EDGE_clip4, 3},
    {"_EDGE_opt_epoch", (DL_FUNC) &_EDGE_opt_epoch, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_EDGE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
