# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

affinity <- function(dat, n_wl, n_dm, nk, H = 1017881L, seed = 5489L) {
    .Call(`_EDGE_affinity`, dat, n_wl, n_dm, nk, H, seed)
}

clip4 <- function(x, inner, outer) {
    .Call(`_EDGE_clip4`, x, inner, outer)
}

opt_epoch <- function(embedding, pairs, adjust, nns, abg, alpha) {
    .Call(`_EDGE_opt_epoch`, embedding, pairs, adjust, nns, abg, alpha)
}

